### ISSUE TITLE
playing .hca but only noise spawn out..

### ISSUE THREAD

**Issue by AkagiShiroe** [kode54/vgmstream#101]
heres some example : https://my.pcloud.com/publink/show?code=XZJh6GZLJodIog2eqS1zfnXxAuyP0MvprMX
game are fate grand order (android).. could you help me please?

**Comment by kode54** [comment]
Please see the hcs64.com forum, and possibly vgm.hcs64.com. These files are likely encrypted, and the key is embedded in the game.
