### ISSUE TITLE
FSB4 files not recognised as containers

### ISSUE THREAD

**Issue by Xehanort88** [kode54/vgmstream#111]
Dragon Age: Origins FSB4 files aren't recognised as containers: only one track plays.
Using the Foobar version.

**Comment by bnnm** [comment]
I assume you want vgmstream to "unpack" and show all subtracks when it detects the file is a container.
I think it's technically possible but not sure how hard would be to do with foobar.

Meanwhile you can split the fsb into all subfiles using [fsbii](http://hcs64.com/files/fsbii08.zip) (for FSB1~4, like your file), or [fsb5_split](http://kirby.cyberbotx.com/fsb5_split.exe) (for FSB5).

**Comment by Xehanort88** [comment]
I actually use FSB unpacker - but yes, that's how I imagined that FSB compatibility would work :) thanks!

**Comment by kode54** [comment]
foobar2000 supports multiple subsongs, but the input service has to implement it. It returns how many subsongs it identifies in a given file, an optional input (0-(#-1)) to actual subsong number translator, and the decoder initializer takes the output of that translator, which can be a 1:1 to the input.

**Comment by Xehanort88** [comment]
I do remember that foobar is great for multiple subsongs, but mostly for
flac and cue files. That's what gave me the idea.

Il 24 Lug 2017 4:10 AM, "Christopher Snowhill" <notifications@github.com>
ha scritto:

**Comment by bnnm** [comment]
I'll take a look how .cues work. I was thinking of doing it like .RSN, that manually(?) add all tracks to the playlist.
If you could point to foobar plugin sources with examples that would be great.

There is the matter of adding internal stream selection first but should be easy enough.
Also maybe getting internal track names as well to show while I'm at it.

**Comment by kode54** [comment]
Look at how foo_gep handles multi-track songs. Adding the base file to the playlist automatically adds all contained tracks.

**Comment by Xehanort88** [comment]
I was wondering if there was any progress update on this. Is it proving to be way more difficult than expected?

**Comment by bnnm** [comment]
Still under testing, should be up in a day or two.

**Comment by Xehanort88** [comment]
So it was possible after all. Out of curiosity, was my pointing towards FLAC cue useful?

**Comment by bnnm** [comment]
I was pondering for quite a while how to handle subsongs, and actually didn't know foobar handled .cue until you mentioned it, so you could say so :)

**Comment by Xehanort88** [comment]
Yay!

**Comment by Xehanort88** [comment]
Will this work just for FSB4 or also FSB5 and/or other ones?

**Comment by bnnm** [comment]
Supported: BIK, EA BNK, FSB1-4/FSB5, SCD, SGXD, SXD, RWS, XWB, XWB+XWH.

**Comment by Xehanort88** [comment]
Silly me, thinking you'd stop at FSB :)

**Comment by Xehanort88** [comment]
It works beautifully I have to say.

I notice, however, that the files are looped (not in the sense of loop points, the content is actually repeated from the beginning) at least 2-4 times per each file. I'm not sure this depends on VGM stream, so I'm writing this down just in case.

**Comment by bnnm** [comment]
FSB4 loops are kinda not-right because many games just repeat songs from beginning to end, have loop points saying so, but don't always put flags to indicate looping.
Right now it errs on the side of caution and loops if it looks loopin' enough, so jingles and stuff end up looping when they shouldn't. I'll see if I can adjust detection some more.
It's not related to subsongs tho, happens with single FSB4s too.

**Comment by Xehanort88** [comment]
I see. Are loop points specified in the metadata reliable?

**Comment by bnnm** [comment]
Loops points are reliable, but they are set to beginning/end very often, and I think that's FMOD's default if not explicitly set by the developer. So at times it's hard to know if that's what they really want.

**Comment by Xehanort88** [comment]
I will check, many thanks.

**Comment by Xehanort88** [comment]
Whew, in the 1st game I checked (Dark Souls, PTD) loop points are actually proper ones, not EOF.

**Comment by bnnm** [comment]
I've tweaked it, most jingles/sfx/voices shouldn't loop now.

But some may still loop when shouldn't, as there is no 100% sure way to tell between songs that should loop from beginning to end from those that shouldn't (I have many samples to confirm this).

**Comment by Xehanort88** [comment]
Yay let me try?

**Comment by Xehanort88** [comment]
Any update on this? Should I close the issue, thanks to your excellent work?

**Comment by kode54** [comment]
I suggest closing it only if your files work.

**Comment by bnnm** [comment]
Subsongs work and FSB jingles shouldn't loop now, as best as I could do. Any other problems with this?

**Comment by Xehanort88** [comment]
None on my end... for now at least.
