### ISSUE TITLE
Eternal Darkness. aud files not working

### ISSUE THREAD

**Issue by Xehanort88** [kode54/vgmstream#113]
Eternal Darkness .aud files extracted directly from the image won't work. May I upload one (they aren't big) for your examination?

**Comment by bnnm** [comment]
Yes, please upload a few (not just one) of varying sizes.

**Comment by Xehanort88** [comment]
[Autopsy.zip](https://github.com/kode54/vgmstream/files/1170823/Autopsy.zip)

There you go thanks

**Comment by bnnm** [comment]
Pretty sure it's custom (Silicon Knights) Ogg/Vorbis. I've added other custom Vorbis formats in the past so I think I'll be able to add it too.
This one looks quite straightforward but they are a bit annoying to code so it'll take some time.

**Comment by Xehanort88** [comment]
Why, many thanks

2017-07-24 19:57 GMT+01:00 bnnm <notifications@github.com>:

**Comment by bnnm** [comment]
Added in the last update. Only had voices tho. Oh well, now I know how to parse OggS, hooray.

**Comment by Xehanort88** [comment]
I know, these were the autopsies by Maximillian Roivas.
Many thanks to have actually dedicated the time to such a sectorial need 😊

Da: bnnm
Inviato: lunedì 31 luglio 2017 20:11
A: kode54/vgmstream
Cc: Xehanort88; Author
Oggetto: Re: [kode54/vgmstream] Eternal Darkness. aud files not working (#113)

Added in the last update. Only had voices tho. Oh well, now I know how to parse OggS, hooray.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Questa email Ã¨ stata esaminata alla ricerca di virus da AVG.
http://www.avg.com
