### ISSUE TITLE
Ps3 .scd Kingdom Hearts 2.5 Metadata not read properly

### ISSUE THREAD

**Issue by Xehanort88** [kode54/vgmstream#116]
I noticed that Ps3 Kingdom Hearts 2.5 SCD files do not display metadata properly. Which is weird, because KH1.5 SCDs do. Would you please check that?

[kh25.zip](https://github.com/kode54/vgmstream/files/1209473/kh25.zip)

**Comment by bnnm** [comment]
May be incorrectly ripped, remove the the first 0x10 bytes and should work.

**Comment by Xehanort88** [comment]
It could definitely be a possibility, thanks.

It worked, thanks! Now, I just need to batch the process!
