### ISSUE TITLE
.AFC Container play directly from container with loop points

### ISSUE THREAD

**Issue by Xehanort88** [kode54/vgmstream#122]
Apologies if this is not possible at all.

I was wondering if you'd consider making VGM play AFC archives?
Files inside are Audiokinetic WWise WAV files which can be converted via ww2ogg, but they lose all metadata.
[Wwise_EndGame2_Music.zip](https://github.com/kode54/vgmstream/files/1298694/Wwise_EndGame2_Music.zip)

**Comment by Xehanort88** [comment]
I see, thank you. Are you sure there is no extractor you can recommend?

**Comment by kode54** [comment]
They're a bunch of WEMs appended to each other, so it should be fairly easy to auto extract them. Basically, grab the RIFF tag at the start, grab its length, extract. Rinse and repeat for any RIFF tags following the end of the previous file.

**Comment by Xehanort88** [comment]
I'm not arguing that - I'm just trying to see if there is a way to get the files off without losing metadata or loop points.

**Comment by kode54** [comment]
Yeah, the WEM files probably have metadata and loop points in them. I'm just not sure whether VGMStream can expose that much metadata.

**Comment by bnnm** [comment]
To rip them use [VGMToolbox](https://sourceforge.net/projects/vgmtoolbox/). In the Advanced Cutter select "RIFF Style Header" preset and press load. Then change the ext to .wem, and select your file (see below). All is preserved, the only metadata is markers that vgmstream can't show, and I don't think it has any loop points (should loop fine if found).

![vgmtoolbox](https://user-images.githubusercontent.com/22844311/30489726-4ed8f91e-9a38-11e7-8683-d46d6e2bacdb.png)

That said, some WEM files don't correcty follow the RIFF spec, use caution when using the above method (see [here](https://www.hcs64.com/mboard/forum.php?showthread=8687&showpage=126))
