### ISSUE TITLE
How do I import HCA decryption key using test.exe?

### ISSUE THREAD

**Issue by able1214** [kode54/vgmstream#123]
I'm trying to decrypt some .hca files that are encrypted, and I do have the decryption key. What do I need to do when I use test.exe? Thanks a lot!

**Comment by kode54** [comment]
Paging @bnnm

**Comment by bnnm** [comment]
You need to create a ".hcakey" in the folder containing your .hca files (filename.hcakey also works).
With a hex editor (ex. [HxD](https://mh-nexus.de/en/hxd/)) put your key in hex format (8 bytes, 0-padded).

However I've just implemented an auto HCA key loader, so if you post the key and the name of the game I'll add it so you wouldn't need to do this.

**Comment by able1214** [comment]
Thanks! The key is 0000000001395C51, game is Magia Record.
