### ISSUE TITLE
Unresolved External Symbol

### ISSUE THREAD

**Issue by bxaimc** [kode54/vgmstream#127]
in_vgmstream.obj : error LNK2001: unresolved external symbol _snwprintf

Line 109 in winamp/in_vgmstream.c:  #define wa_snprintf snwprintf

Change was added on Aug 19: Add Winamp subsong handling (disabled)

**Comment by kode54** [comment]
Inviting @bnnm to the play, since he coded that change.

**Comment by bnnm** [comment]
I'll fix this soon (#define wa_snprintf _snwprintf) but VS still gives lots of unicode warnings.
Rightly so, now that I think about it I'm not sure how it can work fine w/ GCC.

I'll have to rethink the implementation so for now I'll remove #define UNICODE_INPUT_PLUGIN

**Comment by bxaimc** [comment]
Still wondering what's causing winamp to not recognize opus wem. Works in xmplay like you said.

**Comment by kode54** [comment]
Sorry, I forgot to update the Win32 dependencies pack I keep on f.losno.co. That's been updated now.
