### ISSUE TITLE
Planescape Torment Enhanced Edition .mus file not working

### ISSUE THREAD

**Issue by Xehanort88** [kode54/vgmstream#129]
I wonder what has changed, since Baldur's Gate 2 .mus files work. As do PSTEE .acm
[music.zip](https://github.com/kode54/vgmstream/files/1363747/music.zip)

**Comment by kode54** [comment]
Paging @bnnm.

**Comment by bnnm** [comment]
They changed from actual ACM to OGG, how nice. .MUS are basically playlists, but they only support Interplay ACM.

I'll give it a thought but I don't think this can be easily implemented.

**Comment by Xehanort88** [comment]
Didn't they do the same for Baldur's Gate EE?

**Comment by bnnm** [comment]
I have no clue, but if it plays I don't think so?

**Comment by Xehanort88** [comment]
I remember the developer saying so, especially for BG2EE - one of their patches upped all music quality

**Comment by bnnm** [comment]
Planescape EE now works.

**Comment by Xehanort88** [comment]
great! What was the issue?

**Comment by bnnm** [comment]
I had to change some technical stuff first to support "playlists" of Ogg (or any codec).

Also I hope you can close resolved issues to avoid cluttering the list.

**Comment by Xehanort88** [comment]
Of course, thank you!
