### ISSUE TITLE
C&C Tiberian Sun Firestorm addon .AUD have errors on ARM?

### ISSUE THREAD

**Issue by kode54** [kode54/vgmstream#132]
```
<*>  hello
<*>  around?
<*>  anyway, I just wanted to ask if it's known bug in vgmstream that .AUD files bugs on ARM but not in x86?
<*>  easiest to notice is with Command & Conquer Tiberian Sun Firestorm addon, scores010022.aud
<*>  there is a constant tone on the background very annoying
<*>  correction, scores010023.aud
```

Paging @bnnm, maybe you know something about testing on ARM? I haven't actually done any builds of any ARM apps to support this, so I don't even know if they mean ARM Linux, ARM Android, iOS? And I don't know if it's due to an endianness issue in that particular decoder, since ARM Linux can choose to be big endian if it wants.

**Comment by haspor** [comment]
it's Android ARM where the bug happens. I don't think it is endianness problem.

**Comment by haspor** [comment]
[audbug.zip](https://github.com/kode54/vgmstream/files/1384364/audbug.zip)

**Comment by kode54** [comment]
Can you verify your own sample on a desktop computer, using a high quality resampler to upsample it to your likely native sample rate? I can’t hear any tones in that file. I thought maybe I heard a mosquito like tone, so I ran a spectrum analysis on it, but found no obvious tones.

**Comment by haspor** [comment]
If you play that audbug.wav with fb2k for Android, you can hear the problem. Odd thing is that you cannot hear it on fb2k for PC.

**Comment by haspor** [comment]
Problem solved, I think. This seems to be SGS8 (Android 7.0) problem only. The .aud and .wav files seem to play fine with other Android OS versions, also works fine with Lineage OS 7.1.2. Surprisingly it also works with SGS6 using Android 7.0. 

Case closed on my behalf.

**Comment by kode54** [comment]
Sounds like the audio player needs to resample that 22050Hz audio up to the output rate, and it's doing a bad job on just the SGS8. Pity.

**Comment by haspor** [comment]
Just FYI, this problem no longer exist in SGS8, probably because of the Oreo update.
