### ISSUE TITLE
No seamless loop on Audacious

### ISSUE THREAD

**Issue by boardfish** [kode54/vgmstream#135]
Using Audacious 3.7.2, I can easily play .brstm files, but with Repeat and No Playlist Advance ticked (implying it'd loop that song only) the loop points in the .brstm are not used. I have tested this with two BRSTM files downloadable from smashcustommusic [here](http://smashcustommusic.com/39238) and [here](http://smashcustommusic.com/84285). The plugin was compiled with the [most recent vgmstream](https://github.com/kode54/vgmstream/commit/4b2f2471d68a082a0d05e36f716432af83b4fe12) available at the time of writing.

EDIT: I think the files may be opening using the ffmpeg plugin - I'm not seeing a listing for vgmstream in the plugin list, unless it's been misnamed.

![2017-10-25-172226_1920x1080_scrot](https://user-images.githubusercontent.com/20680337/32010218-1cfc2e80-b9a9-11e7-8156-d214a6a69c43.png)

**Comment by bnnm** [comment]
It should show in the plugin dialog (as "vgmstream") so I guess it didn't compile/install correctly.

I can only offer you the [build guide](https://github.com/kode54/vgmstream/blob/master/BUILD.md) (I successfully tested Audacious with Linux Mint) as I don't know much about Linux's intricacies.

Once you get it in the plugin list check if FFmpeg is still playing the BRSTM, I can probably adjust the file type priority then.

**Comment by boardfish** [comment]
I followed the build guide to the letter in my initial attempt at installing it. Pretty sure Mint might be Ubuntu at its core anyway, so it's a little confusing as to why it's not working... Is there no way to distribute a compiled version of the plugin? Thanks for continuing to support this.
