### ISSUE TITLE
ast file

### ISSUE THREAD

**Issue by AntonZab** [kode54/vgmstream#137]
Hello. This ast File not playing
https://drive.google.com/file/d/0B0oEDro3cJx-M1VQWmc1QXVlSVU/view?usp=sharing

**Comment by kode54** [comment]
That is an All Sound Tracker module, a format specific to a DOS AWE32/64 EMU8000 song editor and player. As far as I know, no portable or software based players support the format. You'll need to break out a PC with an AWE32/64 and DOS, or an emulator that can simulate the EMU8000.
