### ISSUE TITLE
Not possible to convert Switch audio to any format

### ISSUE THREAD

**Issue by Xehanort88** [kode54/vgmstream#146]
So, I get this message...

> 1 out of 1 tracks converted with major problems.
> 
> Source: "E:\Mario Kart 8 Deluxe (2017-04-28)(Nintendo)\pBGM_N64_RAINBOW_ROAD_N.bfstm" / index: 1
>   An error occurred while writing to file (The encoder has terminated prematurely with code -1 (0xFFFFFFFF); please re-check parameters) : "C:\Users\dgali\Documents\pBGM_N64_RAINBOW_ROAD_N.mp3"
>   Additional information:
>   Encoder stream format: 32000Hz / 4ch / 16bps
>   Command line: "G:\foobar2000\encoders\lame.exe" -S --noreplaygain -b 320 - "pBGM_N64_RAINBOW_ROAD_N.mp3"
>   Working folder: C:\Users\dgali\Documents\
>   
>   Conversion failed: The encoder has terminated prematurely with code -1 (0xFFFFFFFF); please re-check parameters

I have no idea why. 
Track attached.

[pBGM_N64_RAINBOW_ROAD_N.zip](https://github.com/kode54/vgmstream/files/1524172/pBGM_N64_RAINBOW_ROAD_N.zip)

**Comment by kode54** [comment]
You'll notice that it's trying to convert 4 channels. MP3 only supports mono or stereo. You'll need to add a DSP that downmixes to stereo, either through mixing, like the Downmix to Stereo built-in DSP does, or by channel selection, like the third party Channel Mixer is capable of.

**Comment by Xehanort88** [comment]
Oh d'oh, that's what it was. I suppose that on the other hand WAV or OGG would work?

**Comment by kode54** [comment]
Yes, WAV will work, as will Ogg if you're after lossy compression. Ogg Vorbis or Opus, your choice, they'll both work.
