### ISSUE TITLE
Update libmpg123

### ISSUE THREAD

**Issue by bnnm** [kode54/vgmstream#150]
Paging @kode54

Some EALayer3 files needs a bugfix from the very latest libmpg123, plus seeing it's 10 years old it wouldn't hurt to update.

Official Windows build can be found here: [mpg123-1.25.8-x86](http://www.mpg123.de/download/win32/1.25.8/mpg123-1.25.8-x86.zip). Needed:
* mpg123.h
* fmt123.h (new file, just minor defines separated from the above)
* libmpg123-0.dll
* libmpg123-0.dll.def (may need renaming to libmpg123-0.def and adding "LIBRARY libmpg123-0.dll")

The DLL is swap-able, and I tested in pretty much every supported MPEG format and all worked fine, with minor +-1 sample variations (rounding?).

Could you take care of it, should I go ahead and do a PR?

(figured this would be an ok way to notify)

**Comment by kode54** [comment]
Done.
