### ISSUE TITLE
any plans on marking a version number?

### ISSUE THREAD

**Issue by LionNatsu** [kode54/vgmstream#154]
Hi,
I am a Linux distribution maintainer. I found this software is pretty cool (^^♪.

There is a problem, shall we use r1050-8xx-xxxxx as your version number when we package your software? Are there any plans on releasing or tagging a new version?

Sincerely,
Lion Yang

**Comment by bnnm** [comment]
It's up to kode54, but because since I make frequent contributions I don't think there isn't much point making tagged releases. You can use that name but it'll change soon.

**Comment by LionNatsu** [comment]
Thanks. We decided to use a date string for version. Closing this.
