### ISSUE TITLE
Failed opening

### ISSUE THREAD

**Issue by RayNGC** [kode54/vgmstream#160]
I extracted .adx files from .acb using VGMToolbox.
These .adx files can be played by CriAtomPlayer normally with some extra noise. (because of encryption)
I have the decryption key, and that key is also included in the built-in key list.
I made a 8-bytes hex key file following the instruction.
"name.adxkey" under the same folder with the "name.adx" voice file.
(actually the same folder with test.exe)

> streamfile.c
> "(name.ext)key" (per song), "(.ext)key" (per folder)

Then I used the following command:

> test -o name.wav name.adx

It returned "failed opening name.adx"

I tried both two latest build from [https://github.com/bnnm/vgmstream-builds/tree/master/bin](https://github.com/bnnm/vgmstream-builds/tree/master/bin)
 "vgmstream-latest-test-u.zip" 2017-12-10
"vgmstream-r1050-125-g22d7708-test-u.zip" 2016-12-27

**Comment by bnnm** [comment]
Please post the .ADX/ACB (and name of the game preferably) so we could take a look.

**Comment by RayNGC** [comment]
Thanks
The game is "Super Robot Wars X-Omega"
Example files attached
(.acb and .adx files, and that .adx is extracted from the .acb)

[voice.zip](https://github.com/kode54/vgmstream/files/1565536/voice.zip)

**Comment by bnnm** [comment]
The key was missing (it was in the HCA list but not the ADX list), I've added it in the latest version.

ATM adxkeys must be 6 bytes, manually derived from the original 8 byte key (ex. 515236516d31 derived from 0000968A97978A96).

**Comment by RayNGC** [comment]
Thanks very much, it works!
But I am confused about how to derived the 6 bytes key from the original 8 byte key.
Could you explain a little bit more?

**Comment by bnnm** [comment]
Sorry, I incorrectly copied the key here. 165521992944278 (0x0000968A97978A96 in hex) is indeed 0x5152,0x7979,0x152b (2 bytes *3, or 0x51527979152b as a single 6-byte value, which is what .adxkeys expect).

As for how to derive the original key, first see the bottom of [this file](https://github.com/kode54/vgmstream/blob/master/src/meta/adx_keys.h) for the algorithms.
 
Deriving automatically is a bit involved ATM, as it's basically for my own tests:
- uncomment `#define ADX_VERIFY_DERIVED_KEYS 1`, 
- add a fake entry to the key8/9 list
  * `key8: {0x0000,0x0000,0x0000, "(your keystring)",0},`
  * `key9: {0x0000,0x0000,0x0000, NULL,(your keycode)},`
- compile with VGM_DEBUG_OUTPUT
- try to play your ADX file. this will write a bunch of strings, the last one being:
  `key9: pre=0000 0000 0000 vs calc=5152 7979 152b = ko (165521992944278)` >> calc = derived key
- Take the calc value and update the entry and try to play

Type 9 keycodes like your game uses are easy to derive manually though.

**Comment by RayNGC** [comment]
Thanks so much!
I apologize I just missed the algorithms are just right there in the bottom of the file.
