### ISSUE TITLE
atrac9 thing

### ISSUE THREAD

**Issue by haspor** [kode54/vgmstream#168]
Hello, would it be possible to include the atrac9 source instead of the DLL? Those DLLs are no good on Android :)

**Comment by bnnm** [comment]
I think it would make more sense to adjust the build files and stuff so it's easier to link/build against external libs.

Besides I think Android would use a custom vgmstream anyway so it should be easy to copy the C files in that project.

**Comment by haspor** [comment]
No, Android is not using any custom vgmstream. If the library sources works then I suppose I could use them.
