### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by bxaimc** [kode54/vgmstream#169]
@bnnm @kode54 I'm probably doing something wrong, but something broke in my build and it seems I'm also missing a couple of files?

[capture](https://cdn.discordapp.com/attachments/310983015419346944/399048525889011723/Capture.PNG)

**Comment by bnnm** [comment]
I get the same. Seems various foobar files were changed last week to "#include <ATLHelpers/ATLHelpersLean.h>" and other minor files/defs, but I don't see them in the public 2015 SDK (http://www.foobar2000.org/SDK).
Maybe now needs a later SDK version? My google-fu failed me tho.

I guess you could temp revert the changes in this [commit](https://github.com/kode54/vgmstream/commit/cc2944e4f0cd97b218fb10c11068db15e926a5a2).

**Comment by bxaimc** [comment]
I think the new (unreleased) fb2k sdk requires the v141_xp build tools. I grudgingly had to upgrade to VS2017 from 2015. @Thealexbarney was also having issues linking the test.exe.

**Comment by bxaimc** [comment]
Ok, I think I fixed it with a sort of solution. Build tools and a few additions here and there did the trick.

**Comment by bnnm** [comment]
Should it work now with current SDK, or was it released somewhere I'm not looking?

**Comment by bxaimc** [comment]
It should work once @kode54 merges my PR. Everything should be able to build minus foo_input because of the missing sdk file.
