### ISSUE TITLE
Some SCDs either cut off too early or don't play at all (FFT0HD)

### ISSUE THREAD

**Issue by bxaimc** [kode54/vgmstream#171]
@kode54  @bnnm 
While looking back at some of the jingles I may have missed, I came across a bevy of uncooperative SCDs. Would you guys mind taking a look at them? Some examples:
[FFT0HD SCDs](https://drive.google.com/open?id=1zSY2QrkMlFW7DSsiA17mR2Yx0bXGqN3I)

EDIT: [A few more, this time with a PS ADPCM and AT3 (no RIFF)](https://drive.google.com/open?id=1ArLf6oDOV8ty-yTvEWosercZXz1Af_Zu)

**Comment by bnnm** [comment]
All these fail due to subsong issues (never tested those too much, weird tables), I'll try to fix. PS-ADPCM was never seen before tho.

AT3/ADPCM I guess are leftovers from the PSP version? Time to rerip it since joshw only has the internal RIFF .AT3.

**Comment by bxaimc** [comment]
Aye, sounds like a plan.

**Comment by bnnm** [comment]
Fix PR'd if you want to give it a go.
