### ISSUE TITLE
Audacious Vgmstream Settings MIA

### ISSUE THREAD

**Issue by Bonboon228** [kode54/vgmstream#173]
I recently installed a fresh copy of Lubuntu and built Vgmstream on my Audacious setup.
The plug in compiled successfully but the settings options for Vgmstream are not in the plugins menu.

**Comment by bnnm** [comment]
I don't see anything off in the code, can you try to run Audacious in debug mode? (it takes me a while to setup Linux).
`audacious -V` IIRC, it should write a bunch of text, maybe will mention why settings aren't working. What version of Audacious are you using?

**Comment by Bonboon228** [comment]
Version 3.6.2 (Ubuntu Package Version)
The settings are working, but I cannot find the plug in options to change them in audacious.
Otherwise, the plug in works and plays my BRSTMS.

**Comment by kode54** [comment]
Maybe Ubuntu's compiler doesn't handle constexpr properly? I see the prefs initialization is a constexpr mess. Maybe it also needs to be renamed, because Plugin already has a "info" member, and it's initializing it from the parameter to the constructor?

**Comment by bnnm** [comment]
I think we have the same as [other plugins](https://github.com/audacious-media-player/audacious-plugins/), but I see slight variations so maybe there is some subtle bug. I'll try to test but it may take some time.

**Comment by Bonboon228** [comment]
NVM. Package Upgrade and plugin rebuild fixed the problems. Please Close this issue.
