### ISSUE TITLE
can I convert wav back to the original format?

### ISSUE THREAD

**Issue by andrevictor2015** [kode54/vgmstream#179]
Like take the converted wav and convert it back to raki win adpc?

**Comment by kode54** [comment]
No. The closest you can get to that is VGAudio, and that only supports a limited number of formats. This library is mainly for playback, not for replacing game audio with custom tracks.

**Comment by andrevictor2015** [comment]
Thank you for reply

**Comment by andrevictor2015** [comment]
kode54, and if I convert my audio to ms adpcm and rebuild the raki header using the source code of vgmstream? but I dont know rebuild the raki win adpc header :/

**Comment by andrevictor2015** [comment]
sad
