### ISSUE TITLE
Please add support for SSCF files?

### ISSUE THREAD

**Issue by Xehanort88** [kode54/vgmstream#191]
Hello, I have a request, if you please.
SSCF files are PSP audio files containers, which PSound is incapable of decoding completely and AFAIK no SSCF extractor utility exists.

Since now VGMstream can play multiple tracks inside single files (like FSB), I was hoping if you could add this format to the list.

Please find sample attached from Kingdom Hearts BBS US version. Files inside should be ADPCM, but I am not sure.

[346562564.zip](https://github.com/kode54/vgmstream/files/1704169/346562564.zip)

**Comment by bnnm** [comment]
I'll add it to the to-do list.
The actual extension is .scd btw (as seen in FF XI X360), it's an early version of Square Enix's sound format.

**Comment by Xehanort88** [comment]
Thank you bnnm.
If it helps, Dissidia 012 features the same format as well.

So SSCF is a proto-scd?

**Comment by bnnm** [comment]
You could call it .scd v0, but there are minor variations I think. Also used in Crisis Core, Dissidia 1/2, FF XI X360.

**Comment by bnnm** [comment]
I gave another look and your files are incorrectly ripped I'm afraid.

BBS uses the later .scd 'v1', that starts with SEDBSSCF. Your file contains several of those mixed for no reason, so I think whatever tool you used didn't separate the files properly.
Once correctly ripped rename the resulting files to .scd and should play as-is.

Crisis Core, Dissidia and co do use .scd 'v0' though.

**Comment by Xehanort88** [comment]
It's a soundset for battle: they are supposed to work like that, like the Dissidia 012 SSCF. My tools are probably outdated tho, a multi-purpose hyper-ripper. I will try again.

do you want me to upload one Dissidia 012 SSCF?

**Comment by bnnm** [comment]
Your file is incorrectly ripped, no doubt about it. 

If you want to see it for yourself open BBS0.DAT with a hex editor and go to offset 0xD92A000, that's where the file actually starts, size is at 0xD92A010 (value 0xBE50). Your ripper simply thought the file starts at 0xD92A004 and the file size is at 0xD92A00C (value 0x300400) because that's how "v0" .scd work, but this is a "v1" .scd. v1 start with SEDBSSCF, v0 only with SSCF.

I have Dissidia 1/2, those are from the "v0" that only has SSCF and not from v1 like this one.

**Comment by Xehanort88** [comment]
I don't doubt that. I'll give it another try - but you probably are better than me at ripping them.

**Comment by Xehanort88** [comment]
OK, somehow I can't do that. Time to try something different.

**Comment by Xehanort88** [comment]
[dissidia 012 & BBSFM sscf.zip](https://github.com/kode54/vgmstream/files/1714987/dissidia.012.BBSFM.sscf.zip)
Victory at last?

**Comment by bnnm** [comment]
Those are ok now. Rename to scd, BBS works already.

**Comment by Xehanort88** [comment]
Spectacular. Thank you.

**Comment by bnnm** [comment]
SSCF from Dissidia/Crisis Core work now.

**Comment by Xehanort88** [comment]
Thank you so much!

Il giorno lun 20 ago 2018 alle ore 16:04 bnnm <notifications@github.com> ha
scritto:
