### ISSUE TITLE
Nintendo Switch Ubisoft RAKI Support

### ISSUE THREAD

**Issue by bxaimc** [kode54/vgmstream#193]
@bnnm would you mind adding support for these? I suspect it's opus. 
[RaymanLegends_Switch-NX-RAKI.zip](https://github.com/kode54/vgmstream/files/1726366/RaymanLegends_Switch-NX-RAKI.zip)

**Comment by bnnm** [comment]
Switch Opus, will add.

**Comment by bxaimc** [comment]
More fun stuff: 
[JD2017_RAKI_NX-PCM.zip](https://github.com/kode54/vgmstream/files/1729745/JD2017_RAKI_NX-PCM.zip)

**Comment by bxaimc** [comment]
Also, now that we're here: 
[LEGOWorlds-NSW_STINGS-DSP.zip](https://github.com/kode54/vgmstream/files/1729767/LEGOWorlds-NSW_STINGS-DSP.zip)

Not RAKI but maybe something to add to the dsp meta?

**Comment by bnnm** [comment]
RAKI PR'd, I don't think that flavor of DSP is actually directly supported so next time it is.
