### ISSUE TITLE
LittleBigPlanet Vita i_*.fsb (interactive music)

### ISSUE THREAD

**Issue by slashiee** [kode54/vgmstream#194]
The non-interactive fsbs play just fine (including previews for the interactive tracks) but the interactive fsbs themselves do not play.

[LBPVInteractive.zip](https://github.com/kode54/vgmstream/files/1730518/LBPVInteractive.zip)

**Comment by bnnm** [comment]
Those FSB are simply "special" 6ch (Vita-only), which isn't supported at the moment and will add later.

**Comment by bnnm** [comment]
Those files should work now.

Note that they are considered 6ch (not subsongs); if you need to mute channels I suggest [TXTP](https://github.com/bnnm/vgmstream/wiki/TXTP-info)
