### ISSUE TITLE
segfault in init_ffmpeg_config()

### ISSUE THREAD

**Issue by tobiasjakobi** [kode54/vgmstream#195]
Hello,

I noticed some segfault in init_ffmpeg_config() when trying to play some .nop files. vgmstream_cli is linked against ffmpeg 3.2.10.

You can find the (trivial) patch here:
https://www.math.uni-bielefeld.de/~tjakobi/archive/

With this no segfaults anymore, but the file still does not work:
> failed opening bla1.nop

With best wishes,
Tobias

**Comment by bnnm** [comment]
I added your fix, but I think your FFmpeg (assuming you built it yourself?) isn't correctly setup.

For .nop it needs opus decoder which need several uncommon dependencies, see [here](https://github.com/kode54/vgmstream/blob/master/ext_libs/ffmpeg_options.txt) for what we use.

**Comment by tobiasjakobi** [comment]
I used these exact options when building the shared libs.

Also please use git am next time.

**Comment by tobiasjakobi** [comment]
OK, mystery solved. ffmpeg 3.2.10 is just too old. I rebuild against ffmpeg git tip and now the file is parsed correctly.
