### ISSUE TITLE
Update FFmpeg lib

### ISSUE THREAD

**Issue by bnnm** [kode54/vgmstream#205]
(paging @kode54)

FFmpeg needs to be updated for XMAs up to 16 channels, 10ch found in Skylanders SuperChargers.
(the change in their code was done ~2 weeks ago in wmaprodec.c).

Also please add: **--enable-decoder=alac**
Needed for some .caf+ALAC from iOS games like Chrono Trigger, of all things.

**Comment by kode54** [comment]
You'll have to figure out how to build it yourself, then. I can't get the media-autobuild_suite to agree with me any longer, it refuses to accept my options and builds the full library every time.

**Comment by bnnm** [comment]
Thanks, both changes work.

I can build FFmpeg with GCC + swap DLLs (to test changes etc), but I was under the impression MSVC building/linking needed something extra, and your builds would ensure compatibility with your other players.
