### ISSUE TITLE
TXTH: Sample amount for IMA not implemented

### ISSUE THREAD

**Issue by NicknineTheEagle** [kode54/vgmstream#230]
https://github.com/kode54/vgmstream/blob/93838471df717efce0b7ccbd280f249247004188/src/meta/txth.c#L691

Needs to use the proper function from ima_decoder.c: https://github.com/kode54/vgmstream/blob/93838471df717efce0b7ccbd280f249247004188/src/coding/ima_decoder.c#L898

**Comment by kode54** [comment]
@bnnm

**Comment by kode54** [comment]
Neat, I can't assign people who aren't participants.

**Comment by bnnm** [comment]
Fixed
