### ISSUE TITLE
JOE: Incorrect data size

### ISSUE THREAD

**Issue by NicknineTheEagle** [kode54/vgmstream#236]
https://github.com/kode54/vgmstream/blob/254791551b25344f8725bfcc515c425caa568afe/src/meta/ps2_joe.c#L24

Wrong data size for the latter two versions, not supposed to be divided by 2.

**Comment by kode54** [comment]
@bnnm Can you verify?

**Comment by bnnm** [comment]
Yeah copy paste excess. I'll fix it next time, or just remove lines 37 and 41 meanwhile.
