### ISSUE TITLE
Any way to force a specific input format?

### ISSUE THREAD

**Issue by SamusAranX** [kode54/vgmstream#247]
I have a bunch of files here that I'm certain are encoded as some form of headerless NDS ADPCM, but trying to open them with vgmstream results in a `failed opening bgmdata/BGMDATA_00000034.strm` error message.

It'd be great to be able to give vgmstream a hint as to which format it'll be opening.

**Comment by kode54** [comment]
Paging: @bnnm 

Most headerless formats require a .GENH or .TXTP thing.

**Comment by SamusAranX** [comment]
I figured I should maybe add an example file in case I'm totally wrong.
* The headerless ADPCM(?) file: https://i.peterwunder.de/BGMDATA_0005D4AB.raw (11025 Hz, 1 channel, 4-bit samples)
* A 24 bytes long header of sorts that I extracted along with the first file, but wrote into a separate file for easier decoding using `sox`: https://i.peterwunder.de/HEADER_0005D4AB.bin
* What `sox -t vox -e signed-integer -b 4 -r 11025 -c 1 BGMDATA_0005D4AB.raw -r 44100 -b 16 BGMDATA_0005D4AB.wav` got me (warning, loud): https://i.peterwunder.de/BGMDATA_0005D4AB.wav

I couldn't find anything on GENH or TXTP files. Are they documented somewhere?

**Comment by kode54** [comment]
Apparently, the only documentation for GENH and TXTH (sorry, not TXTP) are the source code:

https://github.com/kode54/vgmstream/blob/master/src/meta/txth.c

I suggest TXTP, as all you need for that is a text editor, and you need to create either:

```
filename.raw.txtp
.raw.txtp
.txtp
```

It will search for them in that order, and if it finds one, it will use it to describe the file it is trying to open.

**Comment by bnnm** [comment]
[Here](https://pastebin.com/1h46ZmKS) is some txth info but it's not up to date.
Using GENH/TXTH you can play headerless files, but what they can do is limited. 

If you paste the header before the data, then rename to .rrds they should play in vgmstream (see [this rip](http://2sf.joshw.info/m/Metroid%20Prime%20-%20Hunters%20-%20First%20Hunt%20(2004-11-21)(NST)(Nintendo).7z)).
(the format is IMA ADPCM).
