### ISSUE TITLE
Layered audio files (FFXIII-2) play back at half speed under Linux (Mint 19)

### ISSUE THREAD

**Issue by topher-au** [kode54/vgmstream#248]
Hello,

I extracted the BGM tracks from FFXIII-2 in SCD format, and I have created the appropriate TXTP files for channel masking, however when attempting to play back the extracted audio files using Audacious, I found that the audio from the layered tracks plays at half speed. Single-track audio files play at the correct speed.

I could not figure out what was causing the issue under Linux, but I booted to Windows and tried playing the files using the foobar2000 component and found that they did play back correctly under Windows.

I have included an audio track with TXTP files for each track that should demonstrate the issue.
https://drive.google.com/file/d/1gbF4ox7Fqt8ok_pdady0E3HA1bq54tjX/view?usp=sharing

Linux Mint 19
Audacious version 3.9
vgmstream commit was b535384

**Comment by kode54** [comment]
The Audacious plugin appears to be hard coded to output stereo audio. I don't know if Audacious even supports channel masks.

**Comment by topher-au** [comment]
@bnmm that worked perfectly, thank you

**Comment by topher-au** [comment]
@bnnm That fixes the playback speed, however it now appears that Audacious then treats channels 1 and 2 as the left speaker and channels 3 and 4 as the right speaker, so the audio then only plays out of one speaker at a time.

I fixed this by copying the channel output to multiple channels instead of silencing them, like so:
```
vgmstream.c:959

    if (vgmstream->channel_mask) {
        int ch,s,count,current;

        // iterate channel mask and find out how channels to copy each sample to
        count = 0;
        for(ch = 0; ch < vgmstream->channels; ch++) {
            if((vgmstream->channel_mask >> ch) & 1)
				count++;
        }

        int copies = vgmstream->channels / count;
        for (s = 0; s < sample_count; s++) {
        	current = 0;
            for (ch = 0; ch < vgmstream->channels; ch++) {
                if ((vgmstream->channel_mask >> ch) & 1) {
                	for(int i=0; i < copies; i++) {
            			buffer[s*vgmstream->channels + current] = buffer[s*vgmstream->channels + ch];
            			current++;
                	}
                    continue;
                }
            }
        }
    }
```
I expect that will probably cause issues with other files, so I think a more long-term solution may be to add an option to the TXTP that triggers the copying of the buffer rather than doing it automatically.

**Comment by bnnm** [comment]
That seems like it's mapping 4.0 channels to FL BL FR BR instead of FL FR BR BR so could be an Audacious bug (or Linux audio bug). Didn't see a way to quickly set the Audacious mapping in the plugin code. Maybe other plugin can do it?

Ideally it should only output the number of masked channels, but it seemed like needed quite a bit of work and it was a niche feature, I'll give it some thought.

**Comment by topher-au** [comment]
I haven't got much experience with C, but I decided to have a go at implementing the channel mapping, see my commits here:
https://github.com/topher-au/vgmstream/tree/set-sources

I haven't tested it at all under any other platforms, but it seems to work alright for Audacious. The format is #s1,1,2,2 with each position representing an output channel and the number representing the source channel to copy from.

**Comment by topher-au** [comment]
Alright, so upon further testing I have discovered two things:

1. There is obvious a bug in that code, in that if you (for example) mute channel 1, then try to use channel 1 as the source for channel 3, it will copy the muted sample, so you end up with no sound in either channel.
2. Audacious actually has a channel mixer plugin that completely negates this issue, after enabling it and setting the output channels to 2, the audio is correctly output in stereo.

Therefore, I will close this issue. Thanks for your help.

**Comment by bnnm** [comment]
I think I'll fix the Audacious multichannel bug and use your 'channel source' code later as a base for mapping, if you don't mind.

**Comment by topher-au** [comment]
No worries at all, I actually just realized I forgot about the multichannel bug altogether and was about to submit a PR, but it's literally a one-line change so I'll leave that one to you.

Feel free to use whatever you like from what I've done there, I hope you can find it useful.
