### ISSUE TITLE
Foobar2000 Component: Sounds cut off early

### ISSUE THREAD

**Issue by NicknineTheEagle** [kode54/vgmstream#250]
Ok, so there appears to be some global issue with foobar2000 component where *all* sounds cut off tad bit early (around 20 to 200 samples). I tested various codecs (PlayStation ADPCM, Xbox ADPCM, EX-XA, EA MicroTalk, EALayer3) and it's always present to various extent. This is actually audible with some speech samples. No clue if it's an issue with the component or foobar2000 player itself. This doesn't happen if I use test.exe so this is definitely not a bug in the core library.
I'm using the latest beta version of foobar (1.4 beta 20).

**Comment by bnnm** [comment]
Fascinating. This can be tested using "convert > wav" and comparing with test.exe.

I think it returns false [here](https://github.com/kode54/vgmstream/blob/master/fb2k/foo_vgmstream.cpp#L271) causing foobar to discard the last proper decode_run, will check.

**Comment by kode54** [comment]
That's by design. You have to return the last chunk with `true`, then return `false` on the next call to decode_run. Hence an `eof` variable that gets set when EOF occurs, and gets cleared by either decode initialize, or by decode seeking that doesn't hit EOF.

**Comment by NicknineTheEagle** [comment]
Yep, definitely looks fixed. I'll leave it open in case @kode54 would like to comment further.
