### ISSUE TITLE
EAAC: EA-XMA not played properly [Need for Speed: The Run (X360)]

### ISSUE THREAD

**Issue by NicknineTheEagle** [kode54/vgmstream#252]
I've extracted the audio chunks from X360 version of NFS: The Run and only the first few fractions of a second are played for each sound. Seems like it only plays the first data block. Could be FFmpeg bug.

Samples:
https://www83.zippyshare.com/v/9VJVSSDm/file.html

**Comment by AnonBaiter** [comment]
what if it's just bnnm's horrible coding that causes these files not to be played properly?

**Comment by NicknineTheEagle** [comment]
Can we stick to technical discussion here and not attack people needlessly?

**Comment by AnonBaiter** [comment]
whoa i'm not that insensitive
although if you wish i can DAMAGE CONTROL just that

**Comment by NicknineTheEagle** [comment]
Looks like the decoder does not recognize SPS block flags (0x44,0x45) and expects SNS ones (0x00,0x80).

**Comment by bnnm** [comment]
Fixed in the next PR

**Comment by NicknineTheEagle** [comment]
It was a bug in ffmpeg_get_eaxma_virtual_size, right? Have you fixed it like this?
```
/* count all SNS/EAXMA blocks size + padding size */
    while (real_offset < real_end_offset) {
        int max_packets;
        size_t block_size = read_32bitBE(real_offset + 0x00, streamFile);
        /* 0x04(4): decoded samples */
        off_t packets_offset = real_offset + 0x08;

        /* At 0x00(1): block flag
         * - in SNS: 0x00=normal block, 0x80=last block (not mandatory)
         * - in SPS: 0x48=header, 0x44=normal block, 0x45=last block (empty) */
		size_t block_flag = ( block_size & 0xFF000000 ) >> 24;
		if ( block_flag == 0x45 )
			break;

        max_packets = get_block_max_packets(num_streams, packets_offset, streamFile);
        if (max_packets == 0) goto fail;

        /* fixed data_size per block for multichannel, see reads */
        virtual_size += max_packets * num_streams * EAXMA_XMA_PACKET_SIZE;

        real_offset += (block_size & 0x00FFFFFF);

        /* exit on last block just in case, though should reach real_size */
        if ( block_flag == 0x80 )
            break;
    }
```
Cause if you count in 0x45 block it cuts off near the end.

**Comment by bnnm** [comment]
Pretty much, yeah.

**Comment by NicknineTheEagle** [comment]
Alright, cool.
