### ISSUE TITLE
Newer version of g1l not supported?

### ISSUE THREAD

**Issue by DeathChaos25** [kode54/vgmstream#259]
One of the most recent Koei Tecmo games (Final Fantasy Dissidia NT on the PS4) uses the ever common .g1l file extension format, however it seems something is different about them as vgmstream is not working with them.  
  
Some sample bgm files;
https://cdn.discordapp.com/attachments/377899265424621569/469186887106428928/bgm005.g1l
https://cdn.discordapp.com/attachments/377899265424621569/469186927073951755/bgm014.g1l
https://cdn.discordapp.com/attachments/377899265424621569/469186958309195776/bgm105.g1l

**Comment by bxaimc** [comment]
You need to extract the AT9 files inside the G1Ls. They’re only containers and usually have more than one file but in some cases, you’ll find a G1L per song like in Dissidia NT.
