### ISSUE TITLE
Add EA ABK v2 w/ SCHl support

### ISSUE THREAD

**Issue by bnnm** [kode54/vgmstream#264]
(paging @NicknineTheEagle)

ABK v2 are used in some PSP games (The Sims 2 Castaway, MOH Heroes 2).
Uncommenting the version check in init_vgmstream_ea_abk makes streams (ABK+AST, after adding AT3 in PR #263) and some banks playable, but others fail due to bad offsets.

[Samples](https://github.com/kode54/vgmstream/files/2216576/mohh2.zip)

Also there seems to be a name table, you could show subsong names by reading them:
(ex. at line ~262) `read_string(vgmstream->stream_name,max_name_size, name_offset,streamFile)`

**Comment by NicknineTheEagle** [comment]
Huh, this is new, I thought v2 ABKs were only present in 7th-gen games using SNR/SNS. This makes things more complicated.
Regarding string table, I don't think it actually contains sound names, judging from what I've seen in other files.

**Comment by NicknineTheEagle** [comment]
Looking at this further, I think all 4 bytes at 0x04 might be related to format version.

**Comment by NicknineTheEagle** [comment]
This should work in my branch now, try it: https://github.com/kode54/vgmstream/pull/265

**Comment by bnnm** [comment]
Most work now, except for a few that get stuck or just fail: [more samples](https://github.com/kode54/vgmstream/files/2216877/mohh2b.zip)
Included a few empty ABK in case they help you understand the format better.

**Comment by NicknineTheEagle** [comment]
It gets stuck cause you're using setup_schl_streamfile on BNKs which aren't blocked. %)

**Comment by NicknineTheEagle** [comment]
https://github.com/kode54/vgmstream/pull/265/commits/5b5f5036e08845193e527de1a89de2131c8f824f

**Comment by NicknineTheEagle** [comment]
One of the samples from level_101 banks cuts out 4 seconds early. Not sure what's up with that, if I rip out the audio with RIFF header and place into a stand-alone AT3 file then it plays just fine.

**Comment by NicknineTheEagle** [comment]
I'm guessing FFmpeg doesn't take well to excess audio data being present.

**Comment by bnnm** [comment]
Looks fine now.
FFmpeg will ignore RIFF sizes and decode the whole stream, and overall it's fairly buggy, so try to feed valid data only.
