### ISSUE TITLE
'coding_FFmpeg’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by AyraHikari** [kode54/vgmstream#273]
Hi, i'm compile vgmstream on Arch Linux Manjaro, but got error, work on old vgmstream, the error like this

`ea_schl.c: Dalam fungsi ‘init_vgmstream_ea_variable_header’:
ea_schl.c:703:41: peringatan: implicit declaration of function ‘init_ffmpeg_offset’; did you mean ‘init_mpeg_custom’? [-Wimplicit-function-declaration]
                 vgmstream->codec_data = init_ffmpeg_offset(temp_streamFile, start_offset, get_streamfile_size(temp_streamFile));
                                         ^~~~~~~~~~~~~~~~~~
                                         init_mpeg_custom
ea_schl.c:703:39: peringatan: assignment to ‘void *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
                 vgmstream->codec_data = init_ffmpeg_offset(temp_streamFile, start_offset, get_streamfile_size(temp_streamFile));
                                       ^
ea_schl.c:710:39: peringatan: assignment to ‘void *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
                 vgmstream->codec_data = init_ffmpeg_offset(streamFile, start_offset, riff_size);
                                       ^
ea_schl.c:714:38: error: ‘coding_FFmpeg’ undeclared (first use in this function); did you mean ‘coding_FADPCM’?
             vgmstream->coding_type = coding_FFmpeg;
                                      ^~~~~~~~~~~~~
                                      coding_FADPCM
ea_schl.c:714:38: catatan: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [Makefile.autotools:807: ea_schl.lo] Error 1
make[2]: Meninggalkan direktori '/home/tedy/Destop/vgmstream-master/src/meta'
make[1]: *** [Makefile.autotools:537: all-recursive] Error 1
make[1]: Meninggalkan direktori '/home/tedy/Destop/vgmstream-master/src'
make: *** [Makefile.autotools:402: all-recursive] Error 1`

How to fix it?
Thanks

**Comment by kode54** [comment]
Clearly, someone is declaring use of FFmpeg related functions without enclosing them in the requisite macro blocks to prevent them from being compiled if, as in your case, FFmpeg support is disabled.

**Comment by kode54** [comment]
This should be fixed by cca30df28dedea1a6c8c215d50c454d95af69738.
