### ISSUE TITLE
EAAC: EA-XMA decoder issue

### ISSUE THREAD

**Issue by NicknineTheEagle** [kode54/vgmstream#278]
https://github.com/kode54/vgmstream/blob/ae5e218518770df77fddbe5cc593cb9675db1d71/src/coding/ffmpeg_decoder_utils_ea_xma.c#L6-L9

This assumes a streamed sound that is stored in blocks but non-streamed sounds aren't blocked and can easily exceed this limit. I initially wanted to crank up buffer size to fix this, this does the job but is not a very nice fix. So I'll just leave this here.

Here are some samples from NFS: Most Wanted 2005 (X360):
https://www111.zippyshare.com/v/ZPeLGcV3/file.html

**Comment by NicknineTheEagle** [comment]
Almost forgot, those ABK files need my updated code here: https://github.com/kode54/vgmstream/pull/279

**Comment by bnnm** [comment]
This also happens in rare streamed sounds IIRC. I wanted to rewrite it using ea_eaac_streamfile+layered layout (which would be error free and more realistic, in a way), but since it mostly works it wasn't super high in the list, I'll bump it up.

**Comment by bnnm** [comment]
Fixed in the next PR.

Note that looped tracks may click, due to a known FFmpeg bug affecting all XMA.
It's beyond my ability to fix though, so I think it belongs to a separate issue (see #55), and once/if it gets fixed this would automatically sound fine.
