### ISSUE TITLE
Certain AT3 files not playing properly

### ISSUE THREAD

**Issue by twocows** [kode54/vgmstream#28]
The character voice files from Fate/Extra are not playing correctly (after dumping the cpk, it's the folder labeled "cv"). I saw somewhere online that it might be an issue with vgmstream not being able to handle mono at3, but I don't know if that's actually the case.

The files appear to be valid at3 (RIFF header, WAVEfmt, fact, data), and what's more, ffmpeg seems to be able to decode them just fine; it gives some warnings (e.g. [wav @ 000000000036b740] Non-monotonous DTS in output stream 0:0; previous: 5120
0, current: 40960; changing to 51200. This may result in incorrect timestamps in
 the output file.), but it's able to produce valid wav files that play just fine.

Using ffmpeg build 8ff0f6a, 20160326 Win64 static
Using foobar2000 1.3.9
Using vgmstream plugin r1050-32-gec99511 Sep 21 2015

**Comment by kode54** [comment]
This component only supports AT3+, not AT3. Mono or stereo doesn't really factor into that.

**Comment by twocows** [comment]
I'm not sure if they're AT3+ or AT3, though I guess if they're not playing maybe it's the latter. Is there any way to differentiate them just looking at the hex?

**Comment by bnnm** [comment]
I checked and those are ATRAC3 (not plus). The format is 0x270 and which seems to use FFMPEG, but still won't play (didn't check thoroughly why).

**Comment by kode54** [comment]
ATRAC3 (not plus) and FFmpeg are not supported until the day I finally build a Windows version that bundles FFmpeg. Currently, the only versions that bundle FFmpeg are with Cog and DeaDBeeF, both for macOS.

**Comment by kode54** [comment]
Windows bundles FFmpeg, and has done so for over a year now. Closing.
