### ISSUE TITLE
Foobar2000: Incorrect track duration

### ISSUE THREAD

**Issue by NicknineTheEagle** [kode54/vgmstream#281]
If you set the loop setting to "Ignore looping", the component still reports track duration as if looping is enabled.

**Comment by AnonBaiter** [comment]
yeah i just noticed this too at one point
i had to close and then open foobar2000 just so the track durations could get back on track thanks to this stupid bug

**Comment by kode54** [comment]
Shift-right-click and reload metadata. The file time stamps haven’t changed, so the info doesn’t refresh automatically.

**Comment by NicknineTheEagle** [comment]
This happens even with files I never loaded before. I don't think caching is the problem, at least not not entirely.

**Comment by bnnm** [comment]
I tried (foobar 1.3, latest vgmstream) disabling looping, loading a some .adx and it shows the correct time (ex. 1:49). Then if I enable looping (normal, 2 loops), "shift-right click > tagging > reload info from file" it's updated correctly (3:35). If disabled and reload again also shows fine for me.
Then again I also get garbage tags at random times so you may be triggering some obscure bug?

**Comment by NicknineTheEagle** [comment]
I reliably get this bug with FSB banks from Hard Reset.

**Comment by bnnm** [comment]
I tried and seems subsongs aren't being properly handled. I can't inmediatedly see why, will test later.

**Comment by bnnm** [comment]
Fixed in the next PR.

**Comment by NicknineTheEagle** [comment]
Was it an issue specifically with FSB parser?

**Comment by bnnm** [comment]
It affected any subsong, wasn't applying "ignore looping" when returning info.
