### ISSUE TITLE
[PS4] Resident Evil 7 (ATRAC9. Audiokinetic Wwise RIFF header. wav to at9 wwise encoder) 

### ISSUE THREAD

**Issue by makc-ar** [kode54/vgmstream#283]
Hi **kode54!** How about import this https://www73.zippyshare.com/v/ZfQlfXip/file.html file?

Here export:
decoding 00000000_en.wem
sample rate: 48000 Hz
channels: 1
stream total samples: 2001402 (41.6959 seconds)
encoding: ATRAC9
layout: flat (no layout)
metadata from: Audiokinetic Wwise RIFF header
bitrate: 96 kbps
samples to play: 2001402 (41.6959 seconds)

Need import  wav to at9 wwise

**Comment by bnnm** [comment]
I don't quite understand? The file works fine.

Or, if you want to convert from a normal .wav AT9 to a Wwise .wem AT9 (or the other way around), I think you should ask in zenhax/xentax for some .bms converter, vgmstream simply decodes audio.
