### ISSUE TITLE
vgmstream never had any trouble grasping VPK files until now (read more for "details")

### ISSUE THREAD

**Issue by AnonBaiter** [kode54/vgmstream#284]
hoo boy look what i just caused with my pull requests regarding VPK files...
[[GOD_OF_WAR_PS2_USA_DEMO]VPK_samples.7z](https://www.sendspace.com/file/cb0yyt)

so basically VPK files can't play through the end at all
that's what happens when i suck at coding - the VPK code is such a screw-up now

**Comment by bnnm** [comment]
I'll fix it next PR.

**Comment by AnonBaiter** [comment]
thank you

**Comment by AnonBaiter** [comment]
i see my issue has been fixed
i'll be closing this now
