### ISSUE TITLE
Close old issues

### ISSUE THREAD

**Issue by bnnm** [kode54/vgmstream#293]
(paging @kode54)

Since I try to resolve them it bothers me a bit they are left open.

I hope you can close the following issues:
- #191, #206, #255, #269, #273 - resolved.
- #141 - WON'T FIX.
- #97, #122, #144, #146, #179, #283 - nothing else to be done.
- #111 - containers/subsongs now work fine.
- #96, #101 - Encrypted HCA keys were added.
- #29 - Already exists.
- #27, #28 - All ATRAC3/p work correctly now (I promise).
- #15 - can be done now with TXTP (no other way I could think off).

**Comment by kode54** [comment]
Closed them all, gave some extra input to a few.
