### ISSUE TITLE
[PS4] Taiko no Tatsujin - Drum Session music files (nus3bank) unable to play

### ISSUE THREAD

**Issue by Johnny165** [kode54/vgmstream#294]
Hi, I recently tried to use the "Taiko no Tatsujin - Drum Session" music files (nus3bank) with the latest vgmstream in foobar and for some reason, it tells me that it's corrupted. I tried other nus3bank files from the same folder and it still says its corrupted when it's actually not. Is there any fix for this? :/

Thanks

**Comment by bnnm** [comment]
I'll fix it soon.

**Comment by bnnm** [comment]
Should work now.
