### ISSUE TITLE
XBOX 4-bit IMA ADPCM (WAD Decibels Explosion)

### ISSUE THREAD

**Issue by Catarax** [kode54/vgmstream#30]
Game : Tony Hawk's Underground 2 (Xbox)
File : music_pcm.wad
Channels : 2
Frequency : 48000
Interleave : 0x18000
Output : genh file

Genh on foobar : 9 tracks of the mix plays perfectly, the rest is an explosion of decibels along with the music.
There is probably something going wrong in the treatement.

I can provide the source files if necessary.

**Screenshot of genh to flac**
![screenshot_1](https://cloud.githubusercontent.com/assets/3964507/15324629/8556bde8-1c47-11e6-8db5-f855668a0088.png)

**Comment by Catarax** [comment]
I can upload the genh if interested.

**Comment by kode54** [comment]
Did this resolve itself or something? I don't know if I dealt with this or not. :[

**Comment by Catarax** [comment]
Hmm I extracted the content of the wad to many xwav files to be able to play them on foobar with vgmstream without trouble. The archive can't be converted directly from what I see.
