### ISSUE TITLE
Second Channel cut too early (Tony Hawk's PS2 Games)

### ISSUE THREAD

**Issue by Catarax** [kode54/vgmstream#31]
When playing a .genh in foobar of Playstation 2 Tony Hawk's games, the second channel is completely cut too early at the end of a track. 

Something goes wrong, however when you convert the whole .wad music file, the second channel ain't cut at the end of each tracks. 
It only happens when you play the music splitted from the HED/WAD archive.

**Here's a list of tracks to hear it :** (headphones will be more useful to detect)

**Tony Hawk's Pro Skater 3 :**
=> CKY - 96 Quite Bitter Beings

**Tony Hawk's Pro Skater 4 :**
=> Gang Starr - Mass Appeal

**Tony Hawk's Underground :**
=> Alkaline Trio - Armageddon

**Tony Hawk's Underground 2 :**
=> Atmosphere - Trying to Find a Balance

**Tony Hawk's American Wasteland**
=> EI-P - Jukie Skate Rock

Others Tony Hawk's games doesn't have this issue because there is enough silence at the end.

Music source: http://psf2.joshw.info/t
I have also tried my own ripping of the tracks with a redump disc, i'm still getting the same channel error at the end also.

Ripping info : 
- 48khz
- 2 channels
- Interleave : 0x18000
- No Loops

**Comment by kode54** [comment]
You did not comment on why you closed this. I would like to know what is or was wrong with those example files. Or was it your sound hardware or DSP setup?

**Comment by Catarax** [comment]
No, this is not an issue with my hardware, I closed it because I have no channels cut when I rip the whole MUSIC.WAD mix in a single file (genh to flac).
Only problems with files splitted directly from MUSIC.HED.

Someone on hcs64.com told me that :
"Assuming it's MIB or something, sounds like an incomplete rip in the source files. Probably missing the last bytes for that channel. Common issue with extracting Sony ADPCM without a file table."

Right now, i'm seeing with Luigi Auriemma if there is not a problem in the decoder.
I've tried 2 tools to decode music.hed and music.wad, same channel output bug.

**You can try this file to hear the channel cut at the end on foobar (headphone recommended) :**
https://mega.nz/#!aQIUnJCY!F2CD1ZqqO2zToolT4xrUIjTFGWKOHhK6L7rFNN5i1jE

I think it's probably an issue coming from vgmstream, thanks for looking at it.
