### ISSUE TITLE
Playback error when trying to play Breath of the Wild music

### ISSUE THREAD

**Issue by roket333** [kode54/vgmstream#313]
Whenever I try to play any sort of music from The Legend of Zelda: Breath of the Wild, I get this
"Unrecoverable playback error: Unknown error code (0x887D0003)"

Edit: Converting the music works just fine, just not playback in the program

**Comment by roket333** [comment]
Nevermind, it's an issue with the program itself
Please ignore this, i'm an idiot

**Comment by kode54** [comment]
It’s an issue with playing what is likely 10 channels or greater at once. Try using .txtp files to pick only one pair of channels.
