### ISSUE TITLE
Crazy Taxi 2 ADX 2:10 max duration (Dreamcast)

### ISSUE THREAD

**Issue by Catarax** [kode54/vgmstream#32]
ADX files from Crazy Taxi 2 (Dreamcast) works on foobar, but can play only until 2:10 of music.
Also the same kind of issue for Crazy Taxi 3 .adx files on Xbox.

**Comment by bnnm** [comment]
I checked and the ADX files seem fine, they just don't contain any loop data.
I assume loop points are manually added in the EXE.

**Comment by Catarax** [comment]
Crazy Taxi 3 really lack of part of music then.
