### ISSUE TITLE
Try to convert genh from taiko wiiu3 but the conversion can't stop

### ISSUE THREAD

**Issue by deadwantsha** [kode54/vgmstream#320]
I dropped the file on test.exe but the conversion didn't stop and the wav's filesize got bigger and bigger, so I have to close the soft in the end. But if I used the old version(r1050) everything works fine. Can you fix this? Thx
Sample genh file:
https://drive.google.com/file/d/1vFIYdcuHxwV45z2qiXXy_Hkc-oZ8ZGj9/view

**Comment by kode54** [comment]
@bnnm

**Comment by bnnm** [comment]
I'll fix it soon.
