### ISSUE TITLE
Yay! Checks now have to be acquired from a marketplace!

### ISSUE THREAD

**Issue by kode54** [kode54/vgmstream#323]
Yay, it looks like I need to reconfigure checks all over again for this repository, and I may have to start paying someone a rental fee for that option. Unless there's just an automatic AppVeyor checks app that I can just add to the repository again?

@bnnm Do you know what's up with this?

**Comment by bnnm** [comment]
Sorry, I don't know anything about AppVeyor and similar autobuilders. Maybe @Thealexbarney could give a hand?

**Comment by Thealexbarney** [comment]
Were checks enabled before? What's GitHub changed?

**Comment by kode54** [comment]
Merely linking the repository with AppVeyor had previously enabled checks on all pull requests, but when they rolled out that marketplace crap, it went away.

**Comment by kode54** [comment]
It only exists on the latest PR. It used to exist on about 20-30 PRs going back, ever since I first enabled AppVeyor. Now it's gone from those PRs and only exists on the single PR that has occurred since I reactivated AppVeyor.
