### ISSUE TITLE
Foobar2000: Subsong crash

### ISSUE THREAD

**Issue by NicknineTheEagle** [kode54/vgmstream#330]
Bug appeared in https://github.com/kode54/vgmstream/commit/ea88c8530478a466e24f18b89fd2c0f5be194c6f, foobar component will crash at https://github.com/kode54/vgmstream/blob/3955ab4bb42b145f15b7f21deead009d80b2c6d5/fb2k/foo_vgmstream.cpp#L449 if it fails to load a subsong for any reason because vgmstream will be NULL.

**Comment by kode54** [comment]
This should be fixed by 401eb1263d1b4889d003f6f1a788575d42022f7a.
