### ISSUE TITLE
impossible to seek backward properly in AWC files

### ISSUE THREAD

**Issue by Mohamed00** [kode54/vgmstream#340]
### Steps to reproduce.
Try to seek backward in an AWC file, example: 30sec_countdown.awc, Grand Theft Auto V (PS3). https://www.dropbox.com/s/sv8p0lb7j5j1cha/30sec_countdown.awc?dl=1
### Expected.
Seeking is successful and playback resumes.
### Actual.
The file seems to seek backward properly, but then becomes silent, and seeking forward does not correct this. This seems to only happen when seeking backward, seeking forward seems to work normally.

**Comment by kode54** [comment]
@bnnm @NicknineTheEagle this seems like a state reset issue? Nothing actually seeks backwards, it starts over and seeks forward. If that’s failing, then the state isn’t being reset properly for that format or file.

**Comment by Mohamed00** [comment]
This seems to happen with all the AWC files from GTA V, not sure about 
Red Dead Redemption or other AWC games yet.

**Comment by bnnm** [comment]
Should be fixed in PR #338

**Comment by Mohamed00** [comment]
This issue is fixed in the latest version of vgmstream. Closing.
