### ISSUE TITLE
Clicking in the beginning of various FSB files from BloodRayne Betrayal (Xbox 360)

### ISSUE THREAD

**Issue by Mohamed00** [kode54/vgmstream#341]
Probably a bad rip, the PS3 MP3 version of this game's soundtrack is even worse, but raising this here in case it isn't. I noticed that several FSBs from BloodRayne Betrayal (Xbox 360), example: https://www.dropbox.com/s/j07yajegexvygr6/02_m_attic_piano.fsb?dl=1, have clicks at the beginning of the tracks. This only seems to happen when the track plays sound immediately, anything that is initially silent is not affected.

**Comment by Mohamed00** [comment]
It happens about 10 minutes in as well, the clicks there and in 
m_attic.fsb seem to be identical. There is an MP3 version of this 
soundtrack for the PS3, and that rip is even worse, weird clicks every 
few seconds constantly, though I'm not sure if that one was converted in 
the ripping process. In either case, if the general consensus is that 
this is an FMOD bug that should be left alone to correctly emulate the 
soundtrack as it would be played in-game, I'll close this.

**Comment by bnnm** [comment]
PS3 MP3 must be reripped as FSB to sound correctly. Clicks at the beginning of songs I don't think are fixable, since data looks fine.
