### ISSUE TITLE
Foobar2000: music not ending correctly after seeking

### ISSUE THREAD

**Issue by bnnm** [kode54/vgmstream#51]
After seeking, music will keep playing until the "expected" playtime has ended, with the seek bar stopped at the end.
Ex. 1:00 long file, if I seek to 0:30, it'll keep playing 1min until ~1:30.

Happens with any looping file, old or new (ex. ADX), doesn't happen in Winamp.
I guess some counter is not being updated (decode_seek/decode_run?).

**Comment by kode54** [comment]
This issue has been fixed by 01b01803ced44d0a4ef537b228cb56c5582eedf3.
