### ISSUE TITLE
Problem with XWAV playback affecting some files

### ISSUE THREAD

**Issue by kode54** [kode54/vgmstream#62]
> Dear Sir,
> just a notice from one of the humble admirers of your foobar2000
> vgmstream coding works.
> Alas, since the beginning of 2017 the updates of 
> foo_input_vgmstream.fb2k-component.zip as well as of 
> vgmstream...-test-u.zip (in cooperation with bnnm I think whose email 
> address I can't come upon so I'm left with pestering you) contain 
> in_vgmstream.dll / xmp-vgmstream.dll / foo_input_vgmstream.dll files 
> that render at least my xwav files (maybe others too) stuttering to 
> unhearable.
> I was lucky enough to get older well working versions from 2016, that is 
> in_vgmstream.dll, r1050-166-g1899a20, 2016-12-27, and xmp-vgmstream.dll, 
> r1050-92-g577df6d, 2016-11-26, but wasn't able to find a corresponding 
> older version of foo_input_vgmstream.dll on the net. My OS is still 
> Windows XP.
> Since I haven't got the slightest notion of coding myself, I hope not to 
> be too brash and not to disturb your workflow too much asking you to 
> have an occasional look at that phenomenon.
> Please excuse my quirky English, my mother language is German. Thank you 
> very much in advance.

[Attachment 2017-01-15.zip](https://github.com/kode54/vgmstream/files/706419/Attachment.2017-01-15.zip)

**Comment by kode54** [comment]
These appear to be normal WAV files. Yet the XWAV parser appears to handle normal WAV files, just with a different 0x0069 codec handler than the riff.c handles them.

**Comment by bnnm** [comment]
Looks like I inadvertedly broke all Xbox codecs samples_per_frame in vgmstream.c (ee5a40224d9b2128a7bf0bd7d4398352e005000c).
I'll upload the fix it soon.

Plus seems riff.c now handles codec 0x0069 just fine so maybe I'll remove xwav.c too.

**Comment by kode54** [comment]
Be aware of how xwav.c handles looping, versus riff.c.
