### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by derselbst** [kode54/vgmstream#76]
@bnnm Build via test/Makefile currently fails when building without ffmpeg support. This line is to blame: [xwb.c:245](https://gitlab.kode54.net/kode54/vgmstream/blob/00523fb5abf0c7e9b2d16939acbe7e92b458eaf2/src/meta/xwb.c#L245) because the `struct xma_sample_data` is enclosed in a `#ifdef VGM_USE_FFMPEG`

**Comment by bnnm** [comment]
Sorry, I'll fix it soon

**Comment by derselbst** [comment]
Thanks!

**Comment by derselbst** [comment]
@bnnm again failing when building without ffmpeg:

```
../src/libvgmstream.a(xwb.o): In function init_vgmstream_xwb:
/src/meta/xwb.c:229: undefined reference to atrac3_bytes_to_samples

../src/libvgmstream.a(wwise.o): In function init_vgmstream_wwise:
/src/meta/wwise.c:114: undefined reference to xma2_parse_fmt_chunk_extra
/src/meta/wwise.c:98: undefined reference to xma2_parse_xma2_chunk
```

**Comment by bnnm** [comment]
Sorry, I keep forgetting. Will fix ASAP.
