### ISSUE TITLE
Help with Compiling

### ISSUE THREAD

**Issue by thecoreyburton** [kode54/vgmstream#81]
I'm a long time user, but only of pre-compiled Winamp binaries. There are a few recent additions to vgmstream that I'm interested in (particularly WWise PCM playback) but compiling from source that isn't my own is not something that's my strong suit. Is there any chance of getting instructions to compile this (I'm using Visual Studio 2015, if that matters) or better yet, a precompiled binary from the latest revision? I do apologize if there's an answer to this listed somewhere, but I did do some searching prior to posting this to no avail.

I also know this probably isn't the right place to be asking this, so I'm going to close this issue as soon as it's posted and leave a tag here ( @bnnm ) so it doesn't clutter the actual issue page.

Sorry for any inconvenience and thank you for reading my request!

**Comment by bnnm** [comment]
Compiled binaries:
* [foobar2000](https://kode54.net/fb2k/foo_input_vgmstream.fb2k-component) (managed by kode54)
* [test/winamp/xmplay](https://github.com/bnnm/vgmstream-builds/raw/master/bin/vgmstream-latest-test-u.zip) (managed by me)

I added [here](https://github.com/kode54/vgmstream/blob/master/BUILD.md) a compiling guide to the best of my ability, I can clarify if you need.

**Comment by thecoreyburton** [comment]
Thank you! No need to clarify, this sorts everything perfectly!
