### ISSUE TITLE
No way to select stream numbers (Only first 3 stereo channels of LittleBigPlanet's interactive FSBs can be accessed)

### ISSUE THREAD

**Issue by slashiee** [kode54/vgmstream#92]
When using vgmstream, we can only access the first three stereo channels of an interactive LittleBigPlanet FSB, even though in the game those interactive tracks are usually twice the amount of that. Going past the those three stereo channels repeats the same ones again but with crackles being added to them. [(example of crackle issue)](https://github.com/kode54/vgmstream/files/1013169/i_pod-3.zip) Using [fsbext](https://github.com/gdawg/fsbext), it's possible to get all the channels from the FSB files using the command -M.

[Sample file (i_pod.fsb)](https://github.com/kode54/vgmstream/files/1013159/i_pod.zip)

**Comment by bnnm** [comment]
Your FSB has 2 streams, and must be split.
FSB has a feature they pack multiple songs (streams) into a single file. Many games just pack EVERY song into a single fsb, so vgmstream can't just play all streams at once as it doesn't make sense.

You can split the fsb into 2 using [fsbii](http://hcs64.com/files/fsbii08.zip) (for FSB1~4, like your file), or [fsb5_split](http://kirby.cyberbotx.com/fsb5_split.exe) (for FSB5)

vgmstream can internally play any stream number, but autoselects the first one as there isn't currently a way for it.

**Comment by Dankfambo25** [comment]
is there a way of making your own music box so that way do don't have to replace the one in game?

**Comment by slashiee** [comment]
@Dankfambo25 this issue isn't for file editing.

**Comment by Dankfambo25** [comment]
Oh sorry

**Comment by bnnm** [comment]
vgmstream can now play all subsongs automatically btw (foobar or winamp, test.exe needs -s N flag)
