### ISSUE TITLE
When I play the .hca file,it`s not music ,it`s noise.

### ISSUE THREAD

**Issue by mengyuxingchen** [kode54/vgmstream#96]
I used foobar2000 and setup the vgmstream components to play the .hca files,but it played noise.
Can you fix it?
Thank you very much.

**Comment by kode54** [comment]
Sounds like it's encrypted. You'll either need to decrypt them, or supply the encryption key as a directory or per-file key file. Maybe @bnnm can help you out?

**Comment by mengyuxingchen** [comment]
oh God，I don`t know how to decrypt them.please help me.Thank you.

**Comment by kode54** [comment]
Please also try searching the hcs64.com forum for your game title, it may already have decryption keys found and posted.

**Comment by mengyuxingchen** [comment]
thanks,I will check it.

**Comment by bnnm** [comment]
You need to:
- create a ".hcakey" file or "(song name).hcakey" in the .hca dir (example)
- open the file with an hex editor (ex. [HxD](https://mh-nexus.de/en/hxd/)) and put the decryption key/number inside
- check if the song now plays

If the HCA has a companion .acb the decryption key may be inside (not sure).
Known keys/numbers you can try:
* from HCA Decoder
CF222F1FE0748978 [Default]
CC55463930DBE1AB [Phantasy Star Online 2]
0000000077EDF21C [Ro-Kyu-Bu! 2? (PSP)]
00000000012C9A53 [Jojo All Star Battle (PS3)]
00003657F27E3B22 [Idolm@ster Cinderella Stage (iOS/Android)]
0011DCDD0DC57F48 [Grimoire (iOS/Android)]
* from 2ch
0000000000000978 [Idol Connect (iOS/Android)]
0000000049913556 [Ro-Kyu-Bu! (Vita)]
00688884A11CCFB0 [Kamen Rider Battle Rush (iOS/Android)]
* from hcs64
00001B85A6AD6125 [SD Gundam Strikers]
00000000012FCFDF [Sonic Runners]
30DBE1ABCC554639 [Old Phantasy Star Online 2]
0000000049913556 [Wax Cube]
0000000000003039 [FGO]
0000000002B99F1A [Raramagi (Mobile)]

If your game isn't listed ther probably won't work though.

**Comment by mengyuxingchen** [comment]
Thank you very much!
