### ISSUE TITLE
in_vgmstream.dll does NOT save/load the config setting to/from .ini??  

### ISSUE THREAD

**Issue by gitatw** [kode54/vgmstream#97]
in_vgmstream.dll
CAN NOT save the in.config setting to the "./plugin.ini",
CAN NOT load the in.config setting from the existed "./plugin.ini".

in_vgmstream.dll does NOT save/load the config setting to/from "./plugin.ini"??
(for winamp2)

**Comment by bnnm** [comment]
Works for me in Winamp 5.x.

In Windows Vista/7/10 it saves the config in C:\Users\(username)\AppData\Roaming\Winamp\Plugins\plugin.ini
Windows XP and earlier I think saves in C:\Program Files\Winamp\Plugins\plugin.ini

**Comment by gitatw** [comment]
Thank you for the reply.

I try to explain about my case a little bit more.
I am calling in_vgmstream.dll as Winamp2.x plugin from my program
without install Winamp.

In this case, can play the sound, 
but CAN NOT save/load the in.config setting to/from "plugin.ini".

"C:\Users(username)\AppData\Roaming\Winamp\Plugins\plugin.ini"
is not created (also folder)ANYWHERE on Windows8.


I want to set the value "Loop forever" in the "in.config" of in_vgmstream.dll(== in_vgmstream configuration).
However the value would back to "Loop normally"(== DEFAULT VALUE) every time
because CAN NOT save/load the setting.
It stops sound in trouble because the setting backs to "Loop Count == 2 & Loop normally" every time.


For example,
is it possible to get the special build version of "DEFAULT VALUE is Loop forever"?
If you can, my problem is to solve.


I always check the update of the below URL:
http://hcs64.com/files/vgmstream/

‎Could you consider it?
Thank you in advance

**Comment by kode54** [comment]
Since you seem intent on implementing Winamp's API, are you implementing the API to retrieve various system paths from the main window's messaging API?
